"""End-to-end MCP demo: data tools + UI bridge tools, captured on video.

Drives a real MCP HTTP session against the unified GUI server while a
Playwright-controlled browser tab subscribes to the bridge. Captures:

- MP4 of the browser tab reacting to bridge commands
- JSON log of every (tool, args, result) call

Both artifacts are written under /tmp first; the runner copies them
into the repo at the end.

Sequence:
  1. list_datasets                     (data: discover)
  2. navigate_to(data tab + dataset)   (bridge: GUI switches view)
  3. get_episode_summary(ep=0)         (data: read)
  4. tag_episode("demo_finding", ...)  (data: comment write)
  5. notify_user("Tagged ...")         (bridge: desktop notification)
  6. get_episode_tags(ep=0)            (data: verify write)
  7. delete_episode_tag("demo_finding")(data: comment delete)
  8. get_episode_tags(ep=0)            (data: verify gone)

Token is issued fresh via TokenStore at startup and revoked at the end.
"""

from __future__ import annotations

import asyncio
import json
import shutil
import sys
import time
from pathlib import Path

sys.path.insert(0, "/home/feit/Documents/lerobot-ai-native/src")

import mcp  # noqa: E402
from mcp import ClientSession  # noqa: E402
from mcp.client.streamable_http import streamablehttp_client  # noqa: E402
from playwright.async_api import async_playwright  # noqa: E402

from lerobot.mcp.auth import SCOPE_COMMENT, SCOPE_READ, TokenStore, default_token_store_path  # noqa: E402

DEMO_NAME = "mcp-e2e-demo"
GUI_URL = "http://127.0.0.1:8000"
MCP_URL = "http://127.0.0.1:8000/mcp/"
REPO_ID = "thewisp/test_leader_follower_do_not_use"
EPISODE_ID = 0
OUT_DIR = Path("/tmp/mcp_e2e_demo")  # nosec B108 — local-only demo scratch
OUT_DIR.mkdir(parents=True, exist_ok=True)


class CallLog:
    """Captures the chat-equivalent transcript: every tool call + response."""

    def __init__(self) -> None:
        self.entries: list[dict] = []

    def add(
        self,
        tool: str,
        args: dict,
        result: object,
        *,
        narrative: str = "",
        verification: dict | None = None,
    ) -> None:
        """Record a tool call plus an optional verification probe.

        ``verification`` is what we observed AFTER the call: a dict with
        keys like ``{"expected": ..., "observed": ..., "ok": True/False,
        "what": "..." (one-line description of what was checked)}``. The
        markdown rendering surfaces this so the artifact shows evidence
        — not just the API's self-reported success.
        """
        # Normalize result for JSON: MCP returns CallToolResult with .content blocks
        if hasattr(result, "content"):
            content = []
            for block in result.content:
                if hasattr(block, "text"):
                    try:
                        content.append(json.loads(block.text))
                    except (json.JSONDecodeError, TypeError):
                        content.append(block.text)
                else:
                    content.append(str(block))
            payload = content[0] if len(content) == 1 else content
        else:
            payload = result
        self.entries.append(
            {
                "tool": tool,
                "args": args,
                "narrative": narrative,
                "result": payload,
                "verification": verification,
                "ts": time.time(),
            }
        )

    def to_json(self) -> str:
        return json.dumps(self.entries, indent=2, default=str)

    def to_markdown(self) -> str:
        lines = [
            "# MCP end-to-end demo — chat transcript",
            "",
            "Generated by `tools/demo_mcp_e2e.py`. Each entry is one MCP tool call:",
            "what the AI asked for (args), what it got back (result), and what was",
            "narrated for the demo. Calls fire against the unified GUI on port 8000;",
            "the matching video frames are in `mcp_e2e_demo.mp4`.",
            "",
        ]
        for i, e in enumerate(self.entries, 1):
            lines.append(f"## {i}. `{e['tool']}`")
            lines.append("")
            if e["narrative"]:
                lines.append(f"_{e['narrative']}_")
                lines.append("")
            lines.append("```json")
            lines.append("// args")
            lines.append(json.dumps(e["args"], indent=2))
            lines.append("")
            lines.append("// result")
            lines.append(json.dumps(e["result"], indent=2, default=str))
            lines.append("```")
            if e.get("verification") is not None:
                v = e["verification"]
                ok = v.get("ok")
                marker = "✓" if ok else ("✗" if ok is False else "·")
                lines.append("")
                lines.append(f"**Verification {marker}** — {v.get('what', '')}")
                lines.append("")
                lines.append("```json")
                lines.append(
                    json.dumps(
                        {k: v.get(k) for k in ("expected", "observed", "ok") if k in v},
                        indent=2,
                        default=str,
                    )
                )
                lines.append("```")
            lines.append("")
        return "\n".join(lines)


async def main() -> None:
    print(f"mcp lib version: {getattr(mcp, '__version__', 'unknown')}")

    # 1. Issue a fresh demo token, mint a clean run.
    store = TokenStore(default_token_store_path())
    # If a prior run left this name in the store, revoke before re-issuing.
    for row in store.list_tokens():
        if row["name"] == DEMO_NAME and row["revoked_at"] is None:
            store.revoke(DEMO_NAME)
    # Also delete revoked rows so the unique name constraint doesn't block reissue.
    store._conn().execute("DELETE FROM tokens WHERE name = ?", (DEMO_NAME,))
    token = store.issue(DEMO_NAME, [SCOPE_READ, SCOPE_COMMENT])
    print(f"issued demo token (length={len(token)})")

    log = CallLog()

    # 2. Start Playwright with video recording; open the GUI.
    async with async_playwright() as p:
        # OOPIF flags are required for smooth video when a cross-origin iframe
        # is present (MeshCat etc.). Doesn't hurt for our case.
        browser = await p.chromium.launch(
            headless=False,
            args=[
                "--disable-features=site-per-process,IsolateOrigins",
                "--no-first-run",
                "--no-default-browser-check",
            ],
        )
        context = await browser.new_context(
            viewport={"width": 1280, "height": 720},
            record_video_dir=str(OUT_DIR / "video_raw"),
            record_video_size={"width": 1280, "height": 720},
            permissions=["notifications"],
        )
        page = await context.new_page()
        await page.goto(GUI_URL)
        # Wait for app + bridge to be ready.
        await page.wait_for_function(
            "() => window.lerobotBridge && window.lerobotBridge.isConnected()",
            timeout=10000,
        )
        await asyncio.sleep(0.6)
        # Title-render small status so the video labels the section.

        async def narrate(text: str) -> None:
            """Inject a status banner into the GUI so the video has captions."""
            await page.evaluate(
                """(text) => {
                    let el = document.getElementById('__demo_banner');
                    if (!el) {
                        el = document.createElement('div');
                        el.id = '__demo_banner';
                        el.style.cssText =
                            'position:fixed;left:0;right:0;bottom:0;z-index:99999;'
                            + 'background:#16213e;color:#4fc3f7;border-top:2px solid #4fc3f7;'
                            + "font:14px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;"
                            + 'padding:10px 16px;letter-spacing:0.3px;';
                        document.body.appendChild(el);
                    }
                    el.textContent = text;
                }""",
                text,
            )

        # 3. Open an MCP session over streamable HTTP with the demo token.
        async with (
            streamablehttp_client(MCP_URL, headers={"Authorization": f"Bearer {token}"}) as (
                read,
                write,
                _,
            ),
            ClientSession(read, write) as session,
        ):
            await session.initialize()
            await narrate("Demo: AI connects via MCP, drives data + UI tools end-to-end")
            await asyncio.sleep(1.2)

            def result_payload(r):
                """Pull the first JSON content block from a CallToolResult."""
                for block in r.content:
                    if hasattr(block, "text"):
                        try:
                            return json.loads(block.text)
                        except (json.JSONDecodeError, TypeError):
                            return block.text
                return None

            # 1. list_datasets — verify count > 0 + the target repo is present
            await narrate("1. list_datasets — AI discovers what's available")
            r = await session.call_tool("list_datasets", {})
            ds_payload = result_payload(r)
            ds_count = len(ds_payload.get("datasets", []) if isinstance(ds_payload, dict) else [])
            has_target = isinstance(ds_payload, dict) and any(
                d.get("repo_id") == REPO_ID for d in ds_payload.get("datasets", [])
            )
            log.add(
                "list_datasets",
                {},
                r,
                narrative="enumerate the local cache",
                verification={
                    "what": "response lists ≥ 1 dataset and includes the target repo_id",
                    "expected": {"count_min": 1, "contains_target_repo_id": REPO_ID},
                    "observed": {"count": ds_count, "contains_target": has_target},
                    "ok": ds_count >= 1 and has_target,
                },
            )
            await asyncio.sleep(1.6)

            # 2. navigate_to(dataset, repo_id) — bridge opens the dataset
            await narrate(f"2. navigate_to(dataset, {REPO_ID}) → GUI opens the dataset")
            r = await session.call_tool(
                "navigate_to",
                {"view": "dataset", "params": {"repo_id": REPO_ID}},
            )
            # Wait for the GUI to fetch + render, then probe the DOM for the
            # opened-dataset signal.
            await asyncio.sleep(3.5)
            dom_state = await page.evaluate(
                """(repoId) => ({
                    opened_repo_ids: Object.keys(window.datasets || {}),
                    rows_for_target: Array.from(
                        document.querySelectorAll(
                            '[data-episode-row][data-dataset-id="' + repoId + '"]'
                        )
                    ).length,
                })""",
                REPO_ID,
            )
            log.add(
                "navigate_to",
                {"view": "dataset", "params": {"repo_id": REPO_ID}},
                r,
                narrative="bridge — GUI navigates to Data tab and opens the dataset's episode tree",
                verification={
                    "what": "target dataset is present in window.datasets and ≥ 1 episode row rendered",
                    "expected": {"target_in_datasets": True, "episode_rows_min": 1},
                    "observed": {
                        "target_in_datasets": REPO_ID in dom_state["opened_repo_ids"],
                        "episode_rows": dom_state["rows_for_target"],
                    },
                    "ok": (REPO_ID in dom_state["opened_repo_ids"] and dom_state["rows_for_target"] >= 1),
                },
            )

            # 2b. navigate_to(episode, repo_id, episode_id) — seek to episode 0
            await narrate("2b. navigate_to(episode, 0) → GUI selects episode 0 in the timeline")
            r = await session.call_tool(
                "navigate_to",
                {
                    "view": "episode",
                    "params": {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
                },
            )
            await asyncio.sleep(2.5)
            dom_state = await page.evaluate(
                """() => ({
                    currentDataset: window.currentDataset,
                    currentEpisode: window.currentEpisode,
                })"""
            )
            log.add(
                "navigate_to",
                {"view": "episode", "params": {"repo_id": REPO_ID, "episode_id": EPISODE_ID}},
                r,
                narrative="bridge — GUI's playback timeline jumps to the requested episode",
                verification={
                    "what": "GUI's currentDataset / currentEpisode reflect the requested target",
                    "expected": {"currentDataset": REPO_ID, "currentEpisode": EPISODE_ID},
                    "observed": dom_state,
                    "ok": (
                        dom_state["currentDataset"] == REPO_ID and dom_state["currentEpisode"] == EPISODE_ID
                    ),
                },
            )

            # 3. get_episode_summary — verify shape: length, duration, etc.
            await narrate(f"3. get_episode_summary(ep={EPISODE_ID}) — AI reads details")
            r = await session.call_tool(
                "get_episode_summary",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
            )
            summary = result_payload(r)
            summary_keys = sorted(summary.keys()) if isinstance(summary, dict) else []
            expected_keys = ["episode_id", "length", "repo_id"]
            log.add(
                "get_episode_summary",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
                r,
                narrative="read length, duration, tasks, existing comments",
                verification={
                    "what": "result is a dict with at least repo_id, episode_id, length keys",
                    "expected": {"keys_superset_of": expected_keys},
                    "observed": {"keys": summary_keys},
                    "ok": all(k in summary_keys for k in expected_keys),
                },
            )
            await asyncio.sleep(1.6)

            # 4. tag_episode — write, then verify the returned tags includes our key
            await narrate("4. tag_episode — writes a sidecar comment (no canonical mutation)")
            tag_value = {
                "outcome": "looks good",
                "written_by": "Claude via MCP",
                "purpose": "end-to-end demo for PR #20",
            }
            r = await session.call_tool(
                "tag_episode",
                {
                    "repo_id": REPO_ID,
                    "episode_id": EPISODE_ID,
                    "key": "demo_finding",
                    "value": tag_value,
                },
            )
            tag_result = result_payload(r)
            tags_after_write = (tag_result or {}).get("tags", {}) if isinstance(tag_result, dict) else {}
            log.add(
                "tag_episode",
                {
                    "repo_id": REPO_ID,
                    "episode_id": EPISODE_ID,
                    "key": "demo_finding",
                    "value": tag_value,
                },
                r,
                narrative="writes to _mcp_annotations.sqlite — dataset files untouched",
                verification={
                    "what": "returned tags dict contains the 'demo_finding' key we just wrote",
                    "expected": {"demo_finding": tag_value},
                    "observed": {"demo_finding": tags_after_write.get("demo_finding")},
                    "ok": tags_after_write.get("demo_finding") == tag_value,
                },
            )
            await asyncio.sleep(1.4)

            # 5. highlight_in_viewer — visible cyan outline + AI badge on the row
            await narrate("5. highlight_in_viewer → bridge outlines the row the AI tagged")
            r = await session.call_tool(
                "highlight_in_viewer",
                {"repo_id": REPO_ID, "episode_ids": [EPISODE_ID]},
            )
            # Sample DOM right after the call to confirm the .bridge-highlight
            # class actually landed on the right row.
            await asyncio.sleep(0.5)
            dom_state = await page.evaluate(
                """({repoId, epId}) => {
                    const sel = '[data-episode-row][data-dataset-id="' + repoId + '"][data-episode-id="' + epId + '"]';
                    const el = document.querySelector(sel);
                    if (!el) return {found: false};
                    const rect = el.getBoundingClientRect();
                    const cs = getComputedStyle(el);
                    return {
                        found: true,
                        has_highlight_class: el.classList.contains('bridge-highlight'),
                        in_view: rect.top >= 0 && rect.bottom <= window.innerHeight,
                        rect_top: rect.top,
                        outline_width: cs.outlineWidth,
                        outline_color: cs.outlineColor,
                        background: cs.backgroundColor,
                    };
                }""",
                {"repoId": REPO_ID, "epId": EPISODE_ID},
            )
            log.add(
                "highlight_in_viewer",
                {"repo_id": REPO_ID, "episode_ids": [EPISODE_ID]},
                r,
                narrative="bridge — matching episode row gets the .bridge-highlight class",
                verification={
                    "what": "the target row has class 'bridge-highlight' and is in viewport",
                    "expected": {"has_highlight_class": True, "in_view": True},
                    "observed": dom_state,
                    "ok": dom_state.get("has_highlight_class") and dom_state.get("in_view"),
                },
            )
            await asyncio.sleep(2.6)  # let the pulse animation finish + dwell

            # 6. get_episode_tags — verify the prior write persisted
            await narrate("6. get_episode_tags — AI confirms the comment landed")
            r = await session.call_tool(
                "get_episode_tags",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
            )
            read_tags = (result_payload(r) or {}).get("tags", {})
            log.add(
                "get_episode_tags",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
                r,
                narrative="read-side: independently confirms the row is on disk",
                verification={
                    "what": "tags dict still contains 'demo_finding' (independent re-read)",
                    "expected": {"demo_finding_present": True},
                    "observed": {"demo_finding_present": "demo_finding" in read_tags},
                    "ok": "demo_finding" in read_tags,
                },
            )
            await asyncio.sleep(1.4)

            # 7. delete_episode_tag — delete returns deleted=True, tags shrink
            await narrate("7. delete_episode_tag — comment-scope deletion")
            r = await session.call_tool(
                "delete_episode_tag",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID, "key": "demo_finding"},
            )
            del_payload = result_payload(r) or {}
            log.add(
                "delete_episode_tag",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID, "key": "demo_finding"},
                r,
                narrative="the missing tool flagged during pre-merge audit; now exposed",
                verification={
                    "what": "result reports deleted=True and 'demo_finding' is no longer in tags",
                    "expected": {"deleted": True, "demo_finding_remaining": False},
                    "observed": {
                        "deleted": del_payload.get("deleted"),
                        "demo_finding_remaining": "demo_finding" in del_payload.get("tags", {}),
                    },
                    "ok": del_payload.get("deleted") is True
                    and "demo_finding" not in del_payload.get("tags", {}),
                },
            )
            await asyncio.sleep(1.4)

            # 8. get_episode_tags — confirm gone, independently
            await narrate("8. get_episode_tags — confirm sidecar is clean")
            r = await session.call_tool(
                "get_episode_tags",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
            )
            final_tags = (result_payload(r) or {}).get("tags", {})
            log.add(
                "get_episode_tags",
                {"repo_id": REPO_ID, "episode_id": EPISODE_ID},
                r,
                narrative="empty tag dict — round-trip closed",
                verification={
                    "what": "tags dict no longer contains 'demo_finding' (independent re-read)",
                    "expected": {"demo_finding_present": False},
                    "observed": {"demo_finding_present": "demo_finding" in final_tags},
                    "ok": "demo_finding" not in final_tags,
                },
            )
            await asyncio.sleep(1.4)

            await narrate("Demo complete — read + comment + bridge surface, end-to-end")
            await asyncio.sleep(2.4)

        # 4. Close to finalize the recording.
        video_path = await page.video.path() if page.video else None
        await context.close()
        await browser.close()

    # 5. Persist artifacts. Playwright writes a .webm; we re-encode to MP4 for
    # broader compatibility in PR previews.
    if video_path:
        src = Path(video_path)
        print(f"raw video: {src} ({src.stat().st_size:,} bytes)")
        mp4_out = OUT_DIR / "mcp_e2e_demo.mp4"
        # Re-encode webm → mp4 (H.264 + AAC). 24fps is plenty.
        import subprocess

        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(src),
                "-c:v",
                "libx264",
                "-crf",
                "28",
                "-preset",
                "fast",
                "-pix_fmt",
                "yuv420p",
                "-movflags",
                "+faststart",
                str(mp4_out),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        print(f"mp4: {mp4_out} ({mp4_out.stat().st_size:,} bytes)")

    json_out = OUT_DIR / "mcp_e2e_demo.json"
    json_out.write_text(log.to_json())
    md_out = OUT_DIR / "mcp_e2e_demo.md"
    md_out.write_text(log.to_markdown())
    print(f"json log: {json_out} ({json_out.stat().st_size:,} bytes, {len(log.entries)} entries)")
    print(f"markdown log: {md_out} ({md_out.stat().st_size:,} bytes)")

    # 6. Revoke the demo token so it doesn't linger.
    store.revoke(DEMO_NAME)
    print("demo token revoked")

    # 7. Clean the raw webm dir.
    # safe-destruct: our own demo scratch dir, fixed path; nothing user-owned
    shutil.rmtree(OUT_DIR / "video_raw", ignore_errors=True)


if __name__ == "__main__":
    asyncio.run(main())
