# Copyright 2026 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Single-file JSON mailbox for click-target requests / responses.

Use case is single-host single-writer-per-side IPC between the GUI
process (driver) and the teleop subprocess (worker). One JSON file:

    {
      "request_seq":  N,
      "response_seq": M,
      "request":  {command, ...args},
      "response": {status, ...data}
    }

Atomicity is the OS rename trick — each write goes to a sibling temp
file then ``rename``s into place. Both sides re-read the whole file
each poll; ``request_seq`` / ``response_seq`` ratchet so a stale
read does no harm (the matching seq is what consumers gate on).

Tradeoffs vs SHM / sockets: simpler code + survives subprocess
crash + easy to inspect with ``cat``. Worst-case latency is
``1 / poll_hz`` per side. Fine for click rates of <1 Hz.
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import tempfile
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class ClickMailbox:
    """File-backed mailbox at ``path``.

    Preconditions:
        * Both sides share a writable filesystem at ``path``.
        * GUI is the sole writer of ``request_*`` fields; teleop is the
          sole writer of ``response_*`` fields. No third party touches
          the file.

    Postconditions:
        * ``post_request(cmd, args)`` increments ``request_seq`` and
          returns the new seq; the response is matched by ``poll_response(seq)``.
        * ``poll_request(last_seen_seq)`` returns ``None`` when no new
          request, else ``(req_seq, request_dict)``.
        * ``post_response(req_seq, data)`` writes ``response_seq=req_seq``
          and the data block; the next GUI poll then resolves.
    """

    def __init__(self, path: str | os.PathLike) -> None:
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if not self.path.exists():
            self._write({"request_seq": 0, "response_seq": 0})

    def _write(self, data: dict[str, Any]) -> None:
        # NamedTemporaryFile inside the same dir, rename — atomic on POSIX.
        d = str(self.path.parent)
        fd, tmp_name = tempfile.mkstemp(prefix=".mailbox.", suffix=".tmp", dir=d)
        try:
            with os.fdopen(fd, "w") as f:
                json.dump(data, f)
            os.replace(tmp_name, self.path)
        except Exception:
            # Cleaning up our own mkstemp scratch file on a failed write;
            # tmp_name was generated by mkstemp() above and is not touched
            # by anything else.
            with contextlib.suppress(FileNotFoundError):
                # safe-destruct: scratch file from mkstemp(), controlled path
                os.unlink(tmp_name)
            raise

    def _read(self) -> dict[str, Any]:
        try:
            with self.path.open("r") as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            return {"request_seq": 0, "response_seq": 0}

    # ── GUI side ─────────────────────────────────────────────────────────

    def post_request(self, command: str, args: dict[str, Any] | None = None) -> int:
        cur = self._read()
        req_seq = int(cur.get("request_seq", 0)) + 1
        cur["request_seq"] = req_seq
        cur["request"] = {"command": command, **(args or {})}
        cur.pop("response", None)
        self._write(cur)
        return req_seq

    def poll_response(self, req_seq: int) -> dict[str, Any] | None:
        cur = self._read()
        if int(cur.get("response_seq", 0)) >= req_seq and "response" in cur:
            return cur["response"]
        return None

    # ── Teleop side ──────────────────────────────────────────────────────

    def poll_request(self, last_seen_seq: int) -> tuple[int, dict[str, Any]] | None:
        cur = self._read()
        req_seq = int(cur.get("request_seq", 0))
        if req_seq > last_seen_seq and "request" in cur:
            return req_seq, cur["request"]
        return None

    def post_response(self, req_seq: int, response: dict[str, Any]) -> None:
        cur = self._read()
        cur["response_seq"] = req_seq
        cur["response"] = response
        self._write(cur)
