// The client decoder must agree with the Python encoder EXACTLY, or masks drawn
// in the browser describe a different region than the one stored in the dataset
// — a disagreement that looks like a slightly-off overlay rather than a bug, and
// would be judged as a bad segmentation instead of a bad decoder.
//
// So the fixtures are generated BY the Python encoder (mask_codec_fixture.json)
// and asserted here against the JS decoder, including the cases that break
// run-length coders: uniform masks with no runs, a checkerboard where every
// pixel is a run, and row-vs-column shapes that only differ if the column-major
// convention is wrong.

const fs = require('fs');
const path = require('path');
const assert = require('assert');

// Load masks.js into this scope; it attaches to `window`.
const src = fs.readFileSync(
    path.join(__dirname, '..', '..', 'src', 'lerobot', 'gui', 'static', 'masks.js'),
    'utf8',
);
global.window = {};
new Function(src)();
const { decodeMask, decodeCounts, entryEnabled } = global.window.MaskOverlay;

const fixtures = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'mask_codec_fixture.json'), 'utf8'),
);
assert.ok(fixtures.length >= 5, 'fixture file looks empty');

let checked = 0;
for (const c of fixtures) {
    const got = decodeMask(c.counts, c.h, c.w);
    assert.strictEqual(got.length, c.h * c.w, `${c.name}: wrong length`);
    for (let i = 0; i < got.length; i++) {
        assert.strictEqual(
            got[i], c.flat_rowmajor[i],
            `${c.name}: pixel ${i} (row ${Math.floor(i / c.w)}, col ${i % c.w}) ` +
            `decoded ${got[i]}, Python encoded ${c.flat_rowmajor[i]}`,
        );
    }
    checked++;
}

// Counts must cover the frame; a truncated string is corruption, not an
// empty mask, and silently returning a blank overlay would hide it.
assert.throws(() => decodeMask(decodeCountsToString([0, 4]), 6, 5), /RLE covers/);
function decodeCountsToString() { return '0' + '4'; }  // deliberately short

// Sign extension: a negative delta round-trips through the 0x10 sign bit.
const counts = decodeCounts('0P1O1');
assert.ok(counts.every((n) => Number.isFinite(n)), 'counts must all be finite');

console.log(`ok - ${checked} Python-generated fixtures decode identically in JS`);

// ── the enabled flag, across the two languages ──────────────────────────────
// `expect_drawn` comes from Python's decode_frame, which is what the trainer
// composites. If JS disagrees, a muted mask is still painted here and the
// operator reads the mute as not having worked -- silent, and wrong in the
// direction that matters.
const frames = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'mask_frame_fixture.json'), 'utf8'),
);
assert.ok(frames.length >= 5, 'frame fixture looks empty');
for (const c of frames) {
    const drawn = c.row.filter(entryEnabled).map((e) => e[0]).sort();
    assert.deepStrictEqual(drawn, c.expect_drawn, `${c.name}: JS and Python disagree`);
}

// The two-element form must never read as disabled: `Boolean(undefined)` is
// false, so destructuring the third element and testing it directly would mute
// every row written before the flag existed.
assert.strictEqual(entryEnabled([0, 'abc']), true, 'a pre-flag entry must read as enabled');
assert.strictEqual(entryEnabled([0, 'abc', 0]), false);
assert.strictEqual(entryEnabled([0, 'abc', 1]), true);
assert.strictEqual(entryEnabled([0, 'abc', true]), true);

console.log(`ok - ${checked} mask cases, ${frames.length} frame cases`);
