"""Regenerate ``mask_naming_fixture.json`` from the Python naming helpers.

The mask column's name is derived in two languages: `mask_feature_of` /
`camera_feature_of` in `datasets/mask_compositing.py`, and `_maskKeyFor` /
`_camKeyFor` in `gui/static/masks.js`. Two implementations of one rule drift,
and the drift is quiet -- the client asks for a column the dataset does not
have, gets nothing, and draws no masks, which reads as "this episode was never
segmented".

So the expected values are generated BY the Python side and asserted against
the JS side, the same arrangement `mask_codec_fixture.json` uses for the RLE
coders. Run this after changing the naming:

    python tests/gui/regen_mask_naming_fixture.py

Cases are chosen for what a hand-rolled swap gets wrong, not for typical
inputs: a camera outside the `.images.` convention, a suffix that itself
contains the infix, a key already in the mask namespace, and a mask key whose
camera lives under a non-standard prefix.
"""

import json
from pathlib import Path

from lerobot.datasets.mask_compositing import camera_feature_of, mask_feature_of

# (camera_key, the dataset's camera keys for the inverse to resolve against)
CASES = [
    ("observation.images.top", ["observation.images.top"]),
    ("observation.images.left_wrist", ["observation.images.left_wrist"]),
    ("observation.images.top_l", ["observation.images.top_l", "observation.images.top_r"]),
    # No `.images.` at all: pusht's key. There is no mask column to derive.
    ("observation.image", ["observation.image"]),
    # A non-standard prefix: the inverse must return the key that exists, not
    # the one the default prefix would produce.
    ("sensors.images.cam0", ["sensors.images.cam0"]),
    # The infix appearing again inside the suffix — only a split with a bound
    # gets this right.
    ("observation.images.rig.images.wrist", ["observation.images.rig.images.wrist"]),
    # Digits and separators that a regex-based swap tends to mangle.
    ("observation.images.cam-0_hi", ["observation.images.cam-0_hi"]),
    # No cameras supplied: the inverse falls back to the standard prefix.
    ("observation.images.top", []),
]


def main() -> None:
    cases = [
        {
            "camera": cam,
            "camera_keys": keys,
            "mask_key": mask_feature_of(cam),
            "camera_roundtrip": camera_feature_of(mask_feature_of(cam), keys),
        }
        for cam, keys in CASES
    ]
    # Keys that name no mask column must come back untouched by the inverse.
    passthrough = ["observation.state", "action", "quality.human_flags", "masks", ""]
    out = {
        "cases": cases,
        "inverse_passthrough": [{"key": k, "expected": camera_feature_of(k, [])} for k in passthrough],
    }
    dest = Path(__file__).parent / "mask_naming_fixture.json"
    dest.write_text(json.dumps(out, indent=2) + "\n")
    print(f"wrote {dest} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
