# Copyright 2026 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
"""The mask column's name is derived in two languages and must agree.

`mask_feature_of` / `camera_feature_of` in `datasets/mask_compositing.py` name
the column for the writer and the reader; `_maskKeyFor` / `_camKeyFor` in
`gui/static/masks.js` name it for the client. Two implementations of one rule
drift, and the drift is quiet: the client asks for a column the dataset does
not have, receives nothing, and draws no masks -- which an operator reads as
"this episode was never segmented".

`mask_naming_fixture.json` is generated by the Python side. Two tests close the
loop: one that the fixture still matches the Python helpers (so changing them
without regenerating fails here rather than silently in the browser), and one
that node agrees with the fixture.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from lerobot.datasets.mask_compositing import camera_feature_of, mask_feature_of

FIXTURE = Path(__file__).parent / "mask_naming_fixture.json"


def _fixture() -> dict:
    return json.loads(FIXTURE.read_text())


def test_the_fixture_matches_the_python_helpers():
    """Catches a change to the Python side that was not regenerated.

    Without this the fixture could go stale and the node test would keep
    passing against yesterday's rule.
    """
    data = _fixture()
    assert data["cases"], "an empty fixture makes every assertion in this file vacuous"
    for case in data["cases"]:
        cam, keys = case["camera"], case["camera_keys"]
        assert mask_feature_of(cam) == case["mask_key"], (
            f"mask_feature_of({cam!r}) changed; rerun tests/gui/regen_mask_naming_fixture.py"
        )
        assert camera_feature_of(case["mask_key"], keys) == case["camera_roundtrip"], (
            f"camera_feature_of({case['mask_key']!r}) changed; rerun the regen script"
        )
    for p in data["inverse_passthrough"]:
        assert camera_feature_of(p["key"], []) == p["expected"]


def test_the_fixture_would_not_be_satisfied_by_identity():
    """The cases must include at least one where the name actually changes, or
    a pair of identity functions would pass every assertion above."""
    data = _fixture()
    assert any(c["mask_key"] != c["camera"] for c in data["cases"])
    assert any(c["camera_roundtrip"] != c["mask_key"] for c in data["cases"])


@pytest.mark.skipif(shutil.which("node") is None, reason="node not installed")
def test_the_client_derives_the_same_names():
    test_js = Path(__file__).parent / "mask_naming.test.js"
    result = subprocess.run(["node", str(test_js)], capture_output=True, text=True, timeout=30)
    assert result.returncode == 0, result.stdout + result.stderr
